### PR TITLE
SDK Refactor for easy extensibility

### PR DESCRIPTION
**Pull request by MattApril**
Here is a re-factored version of the SDK that I wrote.

The new base object APIResource can be easily extended and modeled for various endpoints, or used directly on any unwrapped endpoints (see provided example).

I will admit I'm pushing these changes a bit prematurely, but I am out of town for a week so I tried to quickly clean it up and get it out before I left. It has NOT been tested, outside of the unit tests. Once I get back I will continue development.

### CODE REVIEW

**Comment by richleland** [comment]
Hi @MattApril sorry for the delayed response here! Thanks for the contribution. We're going to be reviewing this over the next few days.

**Comment by bdeanindy** [comment]
While running the tests for this, I received the following error (not sure if Github is honoring the tests for the PR or not).

```
There was 1 failure:

1) SparkPost\Test\SparkPostTest::testGetConfigEmptyException
Failed asserting that exception of type "Exception" is thrown.

FAILURES!
Tests: 43, Assertions: 68, Failures: 1.
```

The logic for that method appears to be alright, but I am going to continue testing and playing with this some more.

**Comment by MattApril** [comment]
I missed that one because I ran the tests individually, and you will find that SparkPostTest passes when run alone.

The reason no exception is thrown is because the config is infact set (see TransmissionTest::setUp). So I would chalk it up to an error in the test; it should clear the config rather than assuming that it is empty and asserting that an exception is thrown.

**Comment by MattApril** [comment]
Committed some minor changes to allow the failing unit test to pass.

**Comment by nornholdj** [comment]
@MattApril: Just wanted to give you an update since its been a while. I'm in the process of reviewing this.     I'm hoping to get some feedback to you early this week.

**Comment by richleland** [comment]
Thanks for the awesome contribution @MattApril - feel free to submit a PR to add yourself to AUTHORS.md - and let us know how that project goes!

**Pull request merged**
