### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by grtumanyan**
Added support for HTTPlug 2.0

### CODE REVIEW

**Comment by andrews05** [comment]
For completeness, you might want to add ` || ^2.0` to the guzzle6-adapter in require-dev too.

**Comment by andrews05** [comment]
@jgzamora Thank you so much for merging this! Can you publish another relase soon? Otherwise composer will still be finding the current release which doesn't include this fix.

**Comment by jgzamora** [comment]
@andrews05 Sorry for the delay! Just published a new release

**Comment by andrews05** [comment]
@jgzamora Awesome, thanks heaps!
I'm not seeing it in composer yet though, is the [GitHub hook](https://packagist.org/about#how-to-update-packages) setup?

**Pull request merged**
