### PR TITLE
Example config

### LINKED ISSUE #19: API Key
See Also: https://github.com/SparkPost/python-sparkpost/issues/51

Caveat to this issue: I maybe misreading the code and there is another way to do this that I am not seeing.

While working on the Java SDK I see this project and Python SDK require the API Key to be set inside a checked in file. [Example](https://github.com/SparkPost/python-sparkpost/blob/master/examples/transmissions/send_transmission.py#L3)

I believe things like that should not be placed inside checked in code because it is too easy to accidentally checkin you key.

I would prefer to see a name something like "config.something.example" that gets checked in. Put "config.something" would be put in the .gitignore so ti is not checked in. The example file would have the place holder properties.

The above filenames should use something appropriate for the language. In Java it would probably be "config.properties.example".

### PR DESCRIPTION
**Pull request by beardyman**
Closes #19

### CODE REVIEW

**Comment by jasonrhodes** [comment]
Not sure if I totally understand how this is _supposed_ to work, but I think it's supposed to auto-generate that example-config file for people after they install this package, but per the composer website:

> Note: Only scripts defined in the root package's composer.json are executed. If a dependency of the root package specifies its own scripts, Composer does not execute those additional scripts.

If it's called "example-config" do we really need to .gitignore it?

**Comment by jasonrhodes** [comment]
Ok so I've got xdebug installed and I'm running `composer test`, it runs tests and generates code coverage but I get the following error output:

```bash
Warning: date(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /Users/jrhodes/php-project/php-sparkpost/vendor/phpunit/php-code-coverage/src/CodeCoverage/Report/HTML.php on line 75

Call Stack:
    0.0002     247568   1. {main}() /Users/jrhodes/php-project/php-sparkpost/vendor/phpunit/phpunit/phpunit:0
    0.0846     593720   2. PHPUnit_TextUI_Command::main() /Users/jrhodes/php-project/php-sparkpost/vendor/phpunit/phpunit/phpunit:56
    0.0846     594344   3. PHPUnit_TextUI_Command->run() /Users/jrhodes/php-project/php-sparkpost/vendor/phpunit/phpunit/src/TextUI/Command.php:138
    0.2867    2639568   4. PHPUnit_TextUI_TestRunner->doRun() /Users/jrhodes/php-project/php-sparkpost/vendor/phpunit/phpunit/src/TextUI/Command.php:186
    6.1857   16081344   5. PHP_CodeCoverage_Report_HTML->process() /Users/jrhodes/php-project/php-sparkpost/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:471
   10.6320   22806344   6. date() /Users/jrhodes/php-project/php-sparkpost/vendor/phpunit/php-code-coverage/src/CodeCoverage/Report/HTML.php:75

 done
```

**Comment by beardyman** [comment]
Its because you don't have a default timezone set in your php.ini file.  

Set: `date.timezone = America/New_York` in php.ini

**Comment by jasonrhodes** [comment]
Nice. OK this LGTM.

**Pull request merged**
