### PR TITLE
Add missing support for inline images

### PR DESCRIPTION
**Pull request by chandon**
Additional mapping in Transmission::$parameterMappings to support inline images.

### CODE REVIEW

**Comment by richleland** [comment]
Thanks for the PR @chandon - we're going to be taking a look at the incoming PRs soon.

**Comment by chandon** [comment]
@richleland no problem, you have till April 27 :)

**Comment by richleland** [comment]
Hi @chandon can you merge in the latest from master - I just merged in the attachments support.

**Comment by chandon** [comment]
You should merge by solving conflict, i've no write access to do that

**Comment by richleland** [comment]
This PR has been merged into master manually. Thanks for the contribution @chandon.

**Pull request closed without merging**
